name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Extract CLASH_VERSION
        id: extract_version
        run: |
          # 使用 grep 和 awk 提取 ARG CLASH_VERSION 的值
          CLASH_VERSION=$(grep "ARG CLASH_VERSION=" Dockerfile | awk -F "=" '{print $2}' | tr -d '"' | tr -d ' \\t\\r\\n')
          # 检查 CLASH_VERSION 是否为空
          if [ -z "$CLASH_VERSION" ]; then
            echo "ERROR: CLASH_VERSION is empty."
            exit 1
          fi
          echo "clash_version=$CLASH_VERSION"
        # 将提取的版本号作为输出
        outputs:
          clash_version: ${{ steps.extract_version.outputs.clash_version }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # 使用从上一个步骤传递的版本号作为镜像的标签，并添加 latest 标签
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clash:${{ steps.extract_version.outputs.clash_version }},${{ secrets.DOCKERHUB_USERNAME }}/clash:latest