name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Extract CLASH_VERSION from Dockerfile
        id: extract_version
        run: |
          # 使用 grep 和 awk 提取 ARG CLASH_VERSION 的值
          CLASH_VERSION=$(grep "ARG CLASH_VERSION=" Dockerfile | awk -F "=" '{print $2}' | tr -d '"' | tr -d ' \\\r\\n')
          echo "CLASH_VERSION=${CLASH_VERSION}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # 使用环境变量作为镜像的标签，并添加 latest 标签
          tags: 9527tech/clash:${CLASH_VERSION},9527tech/clash:latest